import React, { useState } from "react";
import dynamic from "next/dynamic";
import * as Styled from "./stepper.styles";
import * as Step from "./items";

const StepperComponent = dynamic(() => import("@/components/Stepper"), {
  ssr: false,
});

const steps = [
  { label: "Organizational Information" },
  { label: "Cost & Income Information" },
  { label: "Benefits" },
  { label: "Results" },
];

export const ROIStepper: React.FC = () => {
  const [activeStep, setActiveStep] = useState(0);

  const handleNext = (step: number) => {
    setActiveStep(step + 1);
  };

  const handleBack = (step: number) => {
    setActiveStep(step - 1);
  };

  const stepComp = [
    <Step.OrgInfo onNext={handleNext} />,
    <Step.CostInfo onNext={handleNext} onBack={handleBack} />,
    <Step.Benefits onNext={handleNext} onBack={handleBack} />,
    <Step.Results />,
  ];
  return (
    <Styled.ROIStepperWrapper>
      <StepperComponent steps={steps} activeStep={activeStep} />
      <Styled.ROIStepperContainer>
        {stepComp[activeStep]}
        <p>
          {
            "Although great care has been taken to ensure the accuracy and completeness of results derived from this tool, this tool should be used for informational purposes only, and Classe365 makes no warranties, express, implied or statutory, as to the information generated by the tool or any organization’s achievement of the potential benefits estimated by using Classe365 solutions or products. Use, disclosure or reproduction of this tool is prohibited without the prior written permission of Classe365"
          }
        </p>
      </Styled.ROIStepperContainer>
    </Styled.ROIStepperWrapper>
  );
};
